/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentcompanion;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Authenticator;
import java.net.PasswordAuthentication;
import java.net.Socket;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author anmol singh sethi
 */
public class forgotpass extends javax.swing.JFrame {

    DataOutputStream dos;
    DataInputStream dis;
    String email,password,phone,otp;
    
    /**
     * Creates new form forgotpass
     */
    public forgotpass() {
        initComponents();
        jpanel1.setVisible(false);
        jpanel2.setVisible(false);
        
        new Thread(new client()).start();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfroll = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jpanel1 = new javax.swing.JPanel();
        lbotp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfotp = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jpanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("enter roll no.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 87, 110, 40);

        tfroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrollActionPerformed(evt);
            }
        });
        getContentPane().add(tfroll);
        tfroll.setBounds(235, 87, 280, 40);

        jButton1.setText("Fetch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 169, 130, 40);

        jpanel1.setLayout(null);

        lbotp.setText("An OTP is sent to ");
        jpanel1.add(lbotp);
        lbotp.setBounds(40, 30, 790, 30);

        jLabel3.setText("Enter OTP");
        jpanel1.add(jLabel3);
        jLabel3.setBounds(50, 80, 80, 30);
        jpanel1.add(tfotp);
        tfotp.setBounds(170, 80, 210, 22);

        jButton2.setText("Verify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jpanel1.add(jButton2);
        jButton2.setBounds(180, 130, 100, 30);

        getContentPane().add(jpanel1);
        jpanel1.setBounds(40, 230, 590, 170);

        jpanel2.setLayout(null);

        jLabel4.setText("Your password is sent to your email ID");
        jpanel2.add(jLabel4);
        jLabel4.setBounds(160, 40, 232, 30);

        getContentPane().add(jpanel2);
        jpanel2.setBounds(30, 429, 630, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfrollActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String roll= tfroll.getText();
        
        
        try {
            dos.writeBytes("forgot pass\r\n");
            dos.writeBytes(roll+"\r\n");
        } catch (Exception e) {
        }
        jpanel1.setVisible(true);
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                String conotp=tfotp.getText();
                otp=1111+"";
                if(!otp.equals(conotp))
                {
                    JOptionPane.showMessageDialog(rootPane, "Incorrect otp\ntry again");
                }
                else
                {
                   jpanel2.setVisible(true);
                    SimpleMailDemo obj = new SimpleMailDemo(email,"Password Recovery Email","Your password is : "+password);
                   
                   
                }
                     

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jpanel1;
    private javax.swing.JPanel jpanel2;
    private javax.swing.JLabel lbotp;
    private javax.swing.JTextField tfotp;
    private javax.swing.JTextField tfroll;
    // End of variables declaration//GEN-END:variables

   public class client implements Runnable {

        public void run() {
            try {
                Socket sock
                        = new Socket(Credentials.ip, 9000);
                System.out.println("Connected to Server");
                dis = new DataInputStream(sock.getInputStream());
                dos = new DataOutputStream(sock.getOutputStream());

                dos.writeBytes("hello server\r\n");
                while (true) {
                    String s1 = dis.readLine();
                    System.out.println(s1);
                    if(s1.equals("sending response"))
                    {
                        email=dis.readLine();
                        password=dis.readLine();
                        phone=dis.readLine();
                        otp=(int)(1000+8999*Math.random())+"";
                        SMSSender obj=new SMSSender(phone,"your password change otp is "+otp, "text");
                        Thread t=new Thread(obj);
                         t.start();
                         
                    }
                        

                    

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

class SMSSender implements Runnable
{
  Socket sock;
  BufferedReader br,brn;
  InputStreamReader ins;
  PrintWriter pw;
  String s;
  int n;
  char ch[];
  String mobno;
  String msg;
  Statement stmt;
  ResultSet rs;

  String a1[]={" ","?","!","(",")","*","&","@","+","_",";",":",",","\'","=","$","#","<",">","."};
  String a2[]={"%20","%3F","%21","%28","%29","%2A","%26","%40","%2B","%5F","%3B","%3A","%2C","%60","%3D","%24","%23","%3C","%3E","%2E"};
  Thread t;
  String msgtype;
  SMSSender(String mobilenumber,String message,String type)
   {
      mobno=mobilenumber;
      msg=message;
      msgtype=type;
   }
   public void run()
    {
      try
       {
        msg=msg.replace("%","%25");
        for(int i=0;i<a1.length;i++)
       {
         msg=msg.replace(a1[i],a2[i]);
       }
    System.out.println(msg);
    sock=new Socket("enterprise.smsgupshup.com",80);
    pw=new PrintWriter(sock.getOutputStream());
    br=new BufferedReader(new InputStreamReader(sock.getInputStream()));
    pw.println("Get /GatewayAPI/rest?method=SendMessage&send_to="+mobno+"&msg="+msg+"&msg_type="+msgtype+
            "&userid=2000036319&auth_scheme=plain&password=vsssmsserver&v=1.1&format=text HTTP/1.1");
    
//      sock=new Socket("sms.hypecreationz.com",80);
//    pw=new PrintWriter(sock.getOutputStream());
//    br=new BufferedReader(new InputStreamReader(sock.getInputStream()));
//    pw.println("Get /vendorsms/pushsms.aspx?user=VMMEDU&password=123456@&msisdn=9646860043&sid=VMMEDU&msg=test%20message&fl=0 HTTP/1.1");
    
   
    pw.flush();
    pw.println("Accept: text/plain");
    pw.flush();
    pw.println("Accept-Language: en-us");
    pw.flush();
    pw.println("User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)");
    pw.flush();
    pw.println("Host: enterprise.smsgupshup.com");
    pw.flush();
    pw.println("Connection: Close");
    pw.flush();
    pw.println();
    pw.flush();

    while(true)
      {
         s=br.readLine();
         if(s.equals(""))
           {
             break;
           }
       System.out.println(s);
       if(s.indexOf("Content-Length")!=-1)
         {
             n=Integer.parseInt(s.substring(16));
         }
      }
         ch=new char[n];
         br.read(ch,0,n);
         System.out.println(ch);
      }

        catch(Exception e)
          {
            e.printStackTrace();
          }

     }
//    public static void main(String[] args) {
//         SMSSender obj=new SMSSender("7800392141","hello this is test message !!!", "text");
//         Thread t=new Thread(obj);
//         t.start();
//    }
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt;
    private javax.swing.JTextArea jta;
    private javax.swing.JTextField jtf;
    private javax.swing.JLabel response;
 }


}
