/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentcompanion;

/**
 *
 * @author anmol singh sethi
 */
public class notespanel extends javax.swing.JPanel {

    /**
     * Creates new form notespanel
     */
    public notespanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        dateofupload = new javax.swing.JLabel();
        postedby = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setLayout(null);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentcompanion/splash.jpg"))); // NOI18N
        add(icon);
        icon.setBounds(10, 40, 72, 52);

        title.setText("Ttile");
        add(title);
        title.setBounds(50, 40, 157, 52);

        desc.setText("Desc");
        add(desc);
        desc.setBounds(20, 100, 276, 30);

        dateofupload.setText("Posted By");
        add(dateofupload);
        dateofupload.setBounds(20, 140, 276, 30);

        postedby.setText("Date of Upload");
        add(postedby);
        postedby.setBounds(20, 180, 276, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel dateofupload;
    public javax.swing.JLabel desc;
    public javax.swing.JLabel icon;
    public javax.swing.JLabel postedby;
    public javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
