/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentcompanion;

/**
 *
 * @author anmol singh sethi
 */
public class paperpanel extends javax.swing.JPanel {

    /**
     * Creates new form paperpanel
     */
    public paperpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        postedby = new javax.swing.JLabel();
        yearofexamination = new javax.swing.JLabel();
        dateofupload = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentcompanion/splash.jpg"))); // NOI18N
        add(icon);
        icon.setBounds(30, 30, 62, 44);

        title.setText("title");
        add(title);
        title.setBounds(70, 30, 220, 50);

        desc.setText("desc");
        add(desc);
        desc.setBounds(30, 70, 340, 50);

        postedby.setText("postedby");
        add(postedby);
        postedby.setBounds(30, 110, 340, 50);

        yearofexamination.setText("yearofexamination");
        add(yearofexamination);
        yearofexamination.setBounds(30, 170, 330, 40);

        dateofupload.setText("dateofupload");
        add(dateofupload);
        dateofupload.setBounds(30, 220, 340, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel dateofupload;
    public javax.swing.JLabel desc;
    private javax.swing.JLabel icon;
    public javax.swing.JLabel postedby;
    public javax.swing.JLabel title;
    public javax.swing.JLabel yearofexamination;
    // End of variables declaration//GEN-END:variables
}
