/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentcompanion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author anmol singh sethi
 */
public class viewsubject extends javax.swing.JInternalFrame {

    ArrayList<subjectlist> al = new ArrayList<>();
    mymodel model;

    /**
     * Creates new form viewsubject
     */
    public viewsubject() {
        initComponents();
        model = new mymodel();
        jtsub.setModel(model);
        setSize(800, 800);
        fetchData();
        try {
            Class.forName("com.mysql.jdbc.Driver");
//            System.out.println("Driver Loading done");

            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/student_companion", "root", "system");
//            System.out.println("Connection Created");

            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
//            System.out.println("Statement Created");

            ResultSet rs = stmt.executeQuery("select * from departments");
            while (rs.next()) {
                String deptname = rs.getString("department");
                cbdept.addItem(deptname);
            }
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtsub = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbcourse = new javax.swing.JComboBox<>();
        cbdept = new javax.swing.JComboBox<>();
        btfetch = new javax.swing.JButton();
        btdel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(139, 359, 0, 0);

        jtsub.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(jtsub);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 366, 680, 360);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COURSE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 180, 180, 40);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DEPARTMENT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 90, 181, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 240, 850);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        cbcourse.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        cbcourse.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(cbcourse);
        cbcourse.setBounds(40, 180, 240, 40);

        cbdept.setBackground(new java.awt.Color(51, 51, 51));
        cbdept.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        cbdept.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        cbdept.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbdeptItemStateChanged(evt);
            }
        });
        cbdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdeptActionPerformed(evt);
            }
        });
        jPanel2.add(cbdept);
        cbdept.setBounds(40, 90, 240, 40);

        btfetch.setBackground(new java.awt.Color(51, 51, 51));
        btfetch.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        btfetch.setForeground(new java.awt.Color(255, 255, 255));
        btfetch.setText("Fetch Data");
        btfetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfetchActionPerformed(evt);
            }
        });
        jPanel2.add(btfetch);
        btfetch.setBounds(40, 280, 240, 50);

        btdel.setBackground(new java.awt.Color(51, 51, 51));
        btdel.setForeground(new java.awt.Color(255, 255, 255));
        btdel.setText("Delete");
        btdel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelActionPerformed(evt);
            }
        });
        jPanel2.add(btdel);
        btdel.setBounds(60, 750, 230, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(240, 0, 730, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbdeptActionPerformed

    private void cbdeptItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbdeptItemStateChanged
        // TODO add your handling code here:
        String s = (String) cbdept.getSelectedItem();
        cbcourse.removeAllItems();
        try {
            Class.forName("com.mysql.jdbc.Driver");
//            System.out.println("Driver Loading done");

            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/student_companion", "root", "system");
//            System.out.println("Connection Created");

            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
//            System.out.println("Statement Created");

            ResultSet rs = stmt.executeQuery("select * from courses where department='" + s + "'");
            while (rs.next()) {

                cbcourse.addItem(rs.getString("coursename"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbdeptItemStateChanged

    private void btfetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfetchActionPerformed
        fetchData();
    }//GEN-LAST:event_btfetchActionPerformed

    private void btdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelActionPerformed
        if (jtsub.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Select a subject first");
        } else {
            int index = jtsub.getSelectedRow();

            int ans = JOptionPane.showConfirmDialog(this, "are you sure you want to delete this row", "delete row", JOptionPane.YES_NO_OPTION);
            if (ans == JOptionPane.YES_OPTION) {
                String id = al.get(index).subid;

                try {
                    Class.forName("com.mysql.jdbc.Driver");
//            System.out.println("Driver Loading done");

                    Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/student_companion", "root", "system");
//            System.out.println("Connection Created");

                    Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                            ResultSet.CONCUR_UPDATABLE);
//            System.out.println("Statement Created");

                    ResultSet rs = stmt.executeQuery("select * from subjects where subjectcode='" + id + "'");
                    if (rs.next()) {
                        rs.deleteRow();
                        fetchData();

                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btdelActionPerformed

    public void fetchData() {
        try {
            al.clear();
            String course = (String) cbcourse.getSelectedItem();
            Class.forName("com.mysql.jdbc.Driver");
//            System.out.println("Driver Loading done");

            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/student_companion", "root", "system");
//            System.out.println("Connection Created");

            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
//            System.out.println("Statement Created");

            ResultSet rs = stmt.executeQuery("select * from subjects where coursename='" + course + "'");

            while (rs.next()) {
                String subname = rs.getString("subjectname");
                String subid = rs.getString("subjectcode");
                int sem = rs.getInt("semester");
                al.add(new subjectlist(subid, subname, sem));
            }
            model.fireTableDataChanged();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewsubject().setVisible(true);
            }
        });
    }

    class mymodel extends AbstractTableModel {

        @Override
        public int getRowCount() {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            return al.size();
        }

        @Override
        public int getColumnCount() {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            return 3;
        }

        @Override
        public Object getValueAt(int row, int column) {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            subjectlist s = al.get(row);
            if (column == 0) {
                return s.subid;
            } else if (column == 1) {
                return s.subname;
            } else {
                return s.sem;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdel;
    private javax.swing.JButton btfetch;
    private javax.swing.JComboBox<String> cbcourse;
    private javax.swing.JComboBox<String> cbdept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtsub;
    // End of variables declaration//GEN-END:variables
}
